
/*******************************************************************************
       QuestionDialog.h
       This header file is included by QuestionDialog.cc

*******************************************************************************/

#ifndef	_QUESTIONDIALOG_INCLUDED
#define	_QUESTIONDIALOG_INCLUDED

#include <stdio.h>

#ifdef MOTIF
#include <Xm/Xm.h>
#include <Xm/MwmUtil.h>
#include <Xm/DialogS.h>
#include <Xm/MenuShell.h>
#endif /* MOTIF */

#include "UxXt.h"

/*******************************************************************************
       For C++, the method macros translate a method call on an interface
       swidget into a member function call on the interface object.
*******************************************************************************/

#ifndef QuestionDialog_set
#define QuestionDialog_set( UxThis, pEnv, message, title ) \
	(((_UxCQuestionDialog *) UxGetContext(UxThis))->set( pEnv, message, title ))
#endif

#ifndef XKLOADDS
#define XKLOADDS
#endif /* XKLOADDS */

/*******************************************************************************
       The definition of the interface class.
       If you create multiple copies of your interface, the class
       ensures that your callbacks use the variables for the
       correct copy.

       For each swidget in the interface, each argument to the Interface
       function, and each variable in the Interface Specific section of the
       Declarations Editor, there is an entry in the class protected section.
       Additionally, methods generated by the builder are declared as 
       virtual. Wrapper functions are generated for callbacks and actions
       to call the user defined callbacks or actions. A UxDestroyContextCB()
       is also generated to ensure a proper clean up of the class after
       the toplevel is destroyed.
*******************************************************************************/

class _UxCQuestionDialog: public _UxCInterface
{

// Generated Class Members

public:

	// Constructor Function
	_UxCQuestionDialog( swidget UxParent );

	// Destructor Function
	~_UxCQuestionDialog();

	// Interface Function
	Widget	_create_QuestionDialog( void );


	// User Defined Methods
	virtual void set( Environment * pEnv, char *message, char *title );

protected:

	// Widgets in the interface
	Widget	QuestionDialog;

	// Interface Specific Variables
	Widget	mlabel;

	// Arg List of creation function
	swidget	UxParent;

	// Callbacks and their wrappers
	virtual void  okCallback_QuestionDialog(Widget, XtPointer, XtPointer);
	static void  Wrap_okCallback_QuestionDialog(Widget, XtPointer, XtPointer);

	// Callback function to destroy the context
	static void  UxDestroyContextCB(Widget, XtPointer, XtPointer);


	// User Defined Methods

private:
	Widget _build();
	CPLUS_ADAPT_CONTEXT(_UxCQuestionDialog)

	// User Defined Methods


// User Supplied Class Members

} ;


/*******************************************************************************
       Declarations of global functions.
*******************************************************************************/

Widget	create_QuestionDialog( swidget UxParent );

#endif	/* _QUESTIONDIALOG_INCLUDED */
