#include <stdlib.h>
#include <stdio.h>
#include <string.h>

#define ccat(x) (strcat(information,x),strcat(information,"\n"))

void Copyright( int Section )
{
  static char information[20000];
  information[0] = '\0';

  if(Section == 1) {
    ccat("Movie version 2.0, Copyright (C) 1995 Liam Hudson");
    ccat("Movie v2.0 comes with ABSOLUTELY NO WARRANTY; type WARRANTY at prompt for details.");
    ccat("This is free software, and you are welcome to redistribute it");
    ccat("under certain conditions; type LICENSE at command prompt for details");
  }
  if(Section == 2) {
    ccat("                    THIS PROGRAM COMES WITH NO WARRANTY");
    ccat("                    -----------------------------------");
    ccat("1. BECAUSE THE PROGRAM IS LICENSED FREE OF CHARGE, THERE IS NO WARRANTY");
    ccat("   FOR THE PROGRAM, TO THE EXTENT PERMITTED BY APPLICABLE LAW.  EXCEPT WHEN");
    ccat("   OTHERWISE STATED IN WRITING THE COPYRIGHT HOLDERS AND/OR OTHER PARTIES");
    ccat("   PROVIDE THE PROGRAM `AS IS' WITHOUT WARRANTY OF ANY KIND, EITHER EXPRESSED");
    ccat("   OR IMPLIED, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF");
    ccat("   MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.  THE ENTIRE RISK AS");
    ccat("   TO THE QUALITY AND PERFORMANCE OF THE PROGRAM IS WITH YOU@.  SHOULD THE");
    ccat("   PROGRAM PROVE DEFECTIVE, YOU ASSUME THE COST OF ALL NECESSARY SERVICING,");
    ccat("   REPAIR OR CORRECTION.");
    ccat("");
    ccat("2. IN NO EVENT UNLESS REQUIRED BY APPLICABLE LAW OR AGREED TO IN WRITING");
    ccat("   WILL ANY COPYRIGHT HOLDER, OR ANY OTHER PARTY WHO MAY MODIFY AND/OR");
    ccat("   REDISTRIBUTE THE PROGRAM AS PERMITTED ABOVE, BE LIABLE TO YOU FOR DAMAGES,");
    ccat("   INCLUDING ANY GENERAL, SPECIAL, INCIDENTAL OR CONSEQUENTIAL DAMAGES ARISING");
    ccat("   OUT OF THE USE OR INABILITY TO USE THE PROGRAM (INCLUDING BUT NOT LIMITED");
    ccat("   TO LOSS OF DATA OR DATA BEING RENDERED INACCURATE OR LOSSES SUSTAINED BY");
    ccat("   YOU OR THIRD PARTIES OR A FAILURE OF THE PROGRAM TO OPERATE WITH ANY OTHER");
    ccat("   PROGRAMS), EVEN IF SUCH HOLDER OR OTHER PARTY HAS BEEN ADVISED OF THE");
    ccat("   POSSIBILITY OF SUCH DAMAGES.");
    ccat("                    -----------------------------------");
  }
  if(Section == 3) {
    ccat("	        GNU GENERAL PUBLIC LICENSE");
    ccat("   TERMS AND CONDITIONS FOR COPYING, DISTRIBUTION AND MODIFICATION");
    ccat("");
    ccat("  0. This License applies to any program or other work which contains");
    ccat("a notice placed by the copyright holder saying it may be distributed");
    ccat("under the terms of this General Public License.  The 'Program', below,");
    ccat("refers to any such program or work, and a work based on the Program");
    ccat("means either the Program or any derivative work under copyright law:");
    ccat("that is to say, a work containing the Program or a portion of it,");
    ccat("either verbatim or with modifications and/or translated into another");
    ccat("language.  (Hereinafter, translation is included without limitation in");
    ccat("the term modification.)  Each licensee is addressed as you.");
    ccat("");
    ccat("Activities other than copying, distribution and modification are not");
    ccat("covered by this License; they are outside its scope.  The act of");
    ccat("running the Program is not restricted, and the output from the Program");
    ccat("is covered only if its contents constitute a work based on the");
    ccat("Program (independent of having been made by running the Program).");
    ccat("Whether that is true depends on what the Program does.");
    ccat("");
    ccat("  1. You may copy and distribute verbatim copies of the Program's");
    ccat("source code as you receive it, in any medium, provided that you");
    ccat("conspicuously and appropriately publish on each copy an appropriate");
    ccat("copyright notice and disclaimer of warranty; keep intact all the");
    ccat("notices that refer to this License and to the absence of any warranty;");
    ccat("and give any other recipients of the Program a copy of this License");
    ccat("along with the Program.");
    ccat("");
    ccat("You may charge a fee for the physical act of transferring a copy, and");
    ccat("you may at your option offer warranty protection in exchange for a fee.");
    ccat("");
    ccat("  2. You may modify your copy or copies of the Program or any portion");
    ccat("of it, thus forming a work based on the Program, and copy and");
    ccat("distribute such modifications or work under the terms of Section 1");
    ccat("above, provided that you also meet all of these conditions:");
    ccat("");
    ccat("    a) You must cause the modified files to carry prominent notices");
    ccat("    stating that you changed the files and the date of any change.");
    ccat("");
    ccat("    b) You must cause any work that you distribute or publish, that in");
    ccat("    whole or in part contains or is derived from the Program or any");
    ccat("    part thereof, to be licensed as a whole at no charge to all third");
    ccat("    parties under the terms of this License.");
    ccat("");
    ccat("    c) If the modified program normally reads commands interactively");
    ccat("    when run, you must cause it, when started running for such");
    ccat("    interactive use in the most ordinary way, to print or display an");
    ccat("    announcement including an appropriate copyright notice and a");
    ccat("    notice that there is no warranty (or else, saying that you provide");
    ccat("    a warranty) and that users may redistribute the program under");
    ccat("    these conditions, and telling the user how to view a copy of this");
    ccat("    License.  (Exception: if the Program itself is interactive but");
    ccat("    does not normally print such an announcement, your work based on");
    ccat("    the Program is not required to print an announcement.)");
    ccat("");
    ccat("These requirements apply to the modified work as a whole.  If");
    ccat("identifiable sections of that work are not derived from the Program,");
    ccat("and can be reasonably considered independent and separate works in");
    ccat("themselves, then this License, and its terms, do not apply to those");
    ccat("sections when you distribute them as separate works.  But when you");
    ccat("distribute the same sections as part of a whole which is a work based");
    ccat("on the Program, the distribution of the whole must be on the terms of");
    ccat("this License, whose permissions for other licensees extend to the");
    ccat("entire whole, and thus to each and every part regardless of who wrote it.");
    ccat("");
    ccat("Thus, it is not the intent of this section to claim rights or contest");
    ccat("your rights to work written entirely by you; rather, the intent is to");
    ccat("exercise the right to control the distribution of derivative or");
    ccat("collective works based on the Program.");
    ccat("");
    ccat("In addition, mere aggregation of another work not based on the Program");
    ccat("with the Program (or with a work based on the Program) on a volume of");
    ccat("a storage or distribution medium does not bring the other work under");
    ccat("the scope of this License.");
    ccat("");
    ccat("  3. You may copy and distribute the Program (or a work based on it,");
    ccat("under Section 2) in object code or executable form under the terms of");
    ccat("Sections 1 and 2 above provided that you also do one of the following:");
    ccat("");
    ccat("    a) Accompany it with the complete corresponding machine-readable");
    ccat("    source code, which must be distributed under the terms of Sections");
    ccat("    1 and 2 above on a medium customarily used for software interchange; or,");
    ccat("");
    ccat("    b) Accompany it with a written offer, valid for at least three");
    ccat("    years, to give any third party, for a charge no more than your");
    ccat("    cost of physically performing source distribution, a complete");
    ccat("    machine-readable copy of the corresponding source code, to be");
    ccat("    distributed under the terms of Sections 1 and 2 above on a medium");
    ccat("    customarily used for software interchange; or,");
    ccat("");
    ccat("    c) Accompany it with the information you received as to the offer");
    ccat("    to distribute corresponding source code.  (This alternative is");
    ccat("    allowed only for noncommercial distribution and only if you");
    ccat("    received the program in object code or executable form with such");
    ccat("    an offer, in accord with Subsection b above.)");
    ccat("");
    ccat("The source code for a work means the preferred form of the work for");
    ccat("making modifications to it.  For an executable work, complete source");
    ccat("code means all the source code for all modules it contains, plus any");
    ccat("associated interface definition files, plus the scripts used to");
    ccat("control compilation and installation of the executable.  However, as a");
    ccat("special exception, the source code distributed need not include");
    ccat("anything that is normally distributed (in either source or binary");
    ccat("form) with the major components (compiler, kernel, and so on) of the");
    ccat("operating system on which the executable runs, unless that component");
    ccat("itself accompanies the executable.");
    ccat("");
    ccat("If distribution of executable or object code is made by offering");
    ccat("access to copy from a designated place, then offering equivalent");
    ccat("access to copy the source code from the same place counts as");
    ccat("distribution of the source code, even though third parties are not");
    ccat("compelled to copy the source along with the object code.");
    ccat("");
    ccat("  4. You may not copy, modify, sublicense, or distribute the Program");
    ccat("except as expressly provided under this License.  Any attempt");
    ccat("otherwise to copy, modify, sublicense or distribute the Program is");
    ccat("void, and will automatically terminate your rights under this License.");
    ccat("However, parties who have received copies, or rights, from you under");
    ccat("this License will not have their licenses terminated so long as such");
    ccat("parties remain in full compliance.");
    ccat("");
    ccat("  5. You are not required to accept this License, since you have not");
    ccat("signed it.  However, nothing else grants you permission to modify or");
    ccat("distribute the Program or its derivative works.  These actions are");
    ccat("prohibited by law if you do not accept this License.  Therefore, by");
    ccat("modifying or distributing the Program (or any work based on the");
    ccat("Program), you indicate your acceptance of this License to do so, and");
    ccat("all its terms and conditions for copying, distributing or modifying");
    ccat("the Program or works based on it.");
    ccat("");
    ccat("  6. Each time you redistribute the Program (or any work based on the");
    ccat("Program), the recipient automatically receives a license from the");
    ccat("original licensor to copy, distribute or modify the Program subject to");
    ccat("these terms and conditions.  You may not impose any further");
    ccat("restrictions on the recipients' exercise of the rights granted herein.");
    ccat("You are not responsible for enforcing compliance by third parties to");
    ccat("this License.");
    ccat("");
    ccat("  7. If, as a consequence of a court judgment or allegation of patent");
    ccat("infringement or for any other reason (not limited to patent issues),");
    ccat("conditions are imposed on you (whether by court order, agreement or");
    ccat("otherwise) that contradict the conditions of this License, they do not");
    ccat("excuse you from the conditions of this License.  If you cannot");
    ccat("distribute so as to satisfy simultaneously your obligations under this");
    ccat("License and any other pertinent obligations, then as a consequence you");
    ccat("may not distribute the Program at all.  For example, if a patent");
    ccat("license would not permit royalty-free redistribution of the Program by");
    ccat("all those who receive copies directly or indirectly through you, then");
    ccat("the only way you could satisfy both it and this License would be to");
    ccat("refrain entirely from distribution of the Program.");
    ccat("");
    ccat("If any portion of this section is held invalid or unenforceable under");
    ccat("any particular circumstance, the balance of the section is intended to");
    ccat("apply and the section as a whole is intended to apply in other");
    ccat("circumstances.");
    ccat("");
    ccat("It is not the purpose of this section to induce you to infringe any");
    ccat("patents or other property right claims or to contest validity of any");
    ccat("such claims; this section has the sole purpose of protecting the");
    ccat("integrity of the free software distribution system, which is");
    ccat("implemented by public license practices.  Many people have made");
    ccat("generous contributions to the wide range of software distributed");
    ccat("through that system in reliance on consistent application of that");
    ccat("system; it is up to the author/donor to decide if he or she is willing");
    ccat("to distribute software through any other system and a licensee cannot");
    ccat("impose that choice.");
    ccat("");
    ccat("This section is intended to make thoroughly clear what is believed to");
    ccat("be a consequence of the rest of this License.");
    ccat("");
    ccat("  8. If the distribution and/or use of the Program is restricted in");
    ccat("certain countries either by patents or by copyrighted interfaces, the");
    ccat("original copyright holder who places the Program under this License");
    ccat("may add an explicit geographical distribution limitation excluding");
    ccat("those countries, so that distribution is permitted only in or among");
    ccat("countries not thus excluded.  In such case, this License incorporates");
    ccat("the limitation as if written in the body of this License.");
    ccat("");
    ccat("  9. The Free Software Foundation may publish revised and/or new versions");
    ccat("of the General Public License from time to time.  Such new versions will");
    ccat("be similar in spirit to the present version, but may differ in detail to");
    ccat("address new problems or concerns.");
    ccat("");
    ccat("Each version is given a distinguishing version number.  If the Program");
    ccat("specifies a version number of this License which applies to it and any");
    ccat("later version, you have the option of following the terms and conditions");
    ccat("either of that version or of any later version published by the Free");
    ccat("Software Foundation.  If the Program does not specify a version number of");
    ccat("this License, you may choose any version ever published by the Free Software");
    ccat("Foundation.");
    ccat("");
    ccat("  10. If you wish to incorporate parts of the Program into other free");
    ccat("programs whose distribution conditions are different, write to the author");
    ccat("to ask for permission.  For software which is copyrighted by the Free");
    ccat("Software Foundation, write to the Free Software Foundation; we sometimes");
    ccat("make exceptions for this.  Our decision will be guided by the two goals");
    ccat("of preserving the free status of all derivatives of our free software and");
    ccat("of promoting the sharing and reuse of software generally.");
    ccat("");
    ccat("		     END OF TERMS AND CONDITIONS");
    ccat("              -----------------------------------");
  }
  printf("%s\n",information);
}



