/* XPM */
static char * xfit_m_pm[] = {
/* width height ncolors cpp [x_hot y_hot] */
"64 64 5 1 0 0",
/* colors */
" 	s iconColor1	m black	c black",
".	s iconColor2	m white	c white",
"X	s iconColor4	m white	c green",
"o	s iconColor3	m black	c red",
"O	s iconColor5	m black	c blue",
/* pixels */
"                                                                ",
"                                                                ",
"                                                                ",
"                                                                ",
"                 ...    ...  ....     .     ...                 ",
"                .  .   .  .  .   .   ..    .   .                ",
"               .      .      .   .  . .        .                ",
"               .      .      .   .    .        .                ",
"               .      .      .   .    .      ..                 ",
"               .      .      ....     .        .                ",
"               .      .      .        .        .                ",
"                .      .     .        .    .   .                ",
"                 ...    ...  .        .     ...                 ",
"                                                                ",
"                                                                ",
"                                                                ",
"                                                                ",
"     .    .    .    .  XX .    .    .     .    .     .    .     ",
"     .    .    .    . Xoo .    .    .     .    .     .    .     ",
"  ....                o oo                                      ",
"  .....               o oo                                 ..   ",
"     .                o oX                                      ",
"     .               oo oo                                      ",
"  .....              oo oo                                 ..   ",
"     .               oX  o                                      ",
"     .               o   oo                                     ",
"  ....               o   oX                                     ",
"  .....              o   oo                                ..   ",
"     .               o   o o                                    ",
"     .               o   o o                                    ",
"  .....              o   ooX                               ..   ",
"     .              o     oX                                    ",
"     .              o     ooo                                   ",
"  ....              o     o XX                                  ",
"  .....             o     o  XX                            ..   ",
"     .              o     o   Xo                                ",
"     .              o     o    X                                ",
"  .....             o     o  oo X                          ..   ",
"     .             oo      o o oXX                              ",
"     .             o       oo  o XXXXX                          ",
"  ....             o       oo  oo   oo       oo                 ",
"  .....            o       oo   o  o oX      ooo           ..   ",
"     .             o       o    o  o oo     o  o                ",
"     .             o       o    o o   o     o  oo               ",
"  .....           oo       oo    oo   oo   oo   o          ..   ",
"     .            o       ooo    oo   oo   o    o               ",
"     .            o       o o    o     oo  o    o               ",
"  ....            o       o o    o     oX oo     o              ",
"  .....           o       o o   ooo    ooXo      o         ..   ",
"     .           oo      o  o   o o     oXo      oX             ",
"     .           o       o   o  o o     o o       o             ",
"  .....          o      o    o o   o    oo        oX     X ..   ",
"  ....          o      oo    ooo   o     o        XoX oooooo    ",
"     .       XXoooooooooO    oo    oo   o o        oooo    o    ",
"  ....    Oooooooo      oooooooooooo oooo oo       ooooooooo    ",
"  ....OooooX   .    .     .    .    oooooooooooooooooooo  ...   ",
"     XoX....................................................    ",
"         ..    ..   ..    ..   ..   ..    ..   ..    .    ..    ",
"         ..    ..   ..    ..   ..   ..    ..   ..   ..    ..    ",
"                                                                ",
"                                                                ",
"                                                                ",
"                                                                ",
"                                                                "};
