corfunc:
	make -C fortran/corfunc -f Makefile.linux
	make -C fortran/tropus -f Makefile.linux
	make -C java/java_src -f Makefile.linux

clean:
	make -C fortran/corfunc -f Makefile.linux clean
	make -C fortran/tropus -f Makefile.linux clean
	make -C java/java_src -f Makefile.linux clean
	-rm *.jar extract_par extrapolate ftransform tropus
